on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            archive-format: zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive-format: tar.gz tar.xz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive-format: zip
    name: Release for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: brew install michaeleisel/zld/zld
        if: matrix.os == 'macos-latest'
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive-format }}
          EXTA_FILES: 'LICENSE.md README.md'